### ISSUE TITLE
Repeat work on unit settings when a variable does not exist

### ISSUE THREAD

**Issue by lavea** [QuantiModo/quantimodo-android-chrome-ios-web-app#1063]
1. Currently to add a reminder: If variable name does not exist from searching result.  Flow:  Compulsory select category, unit..)-->Added. In this case, the variable named is INR ( International Normalized Ratio).
2. From reminder-inbox, select INR to add measurement. Then the user has to select again category, unit....
Suggestion: Accept those units as default settings after the user sets it ready during reminder adding process. 
Or is there any other reason to be like this?

**Comment by mikepsinn** [comment]
What is the unit you're using?

**Comment by lavea** [comment]
Second. To test blood clotting time. Was considering to add this to my default variables.

**Comment by mikepsinn** [comment]
I think I've fixed this.  Can you let me know if you still have the problem?  Thanks!

**Comment by lavea** [comment]
Thanks! The settings with this particular variable are solved. Maybe I did not explain clearly. Actually, I am thinking if it is possible to design a logic that takes category and unit settings made by users as a default.  And no matter of what the variable is.  After that, when edit or add a new measurement, no such setting anymore needed if the user doesn't want to change those settings. Because it is done already during adding new reminder process.

**Comment by lavea** [comment]
Just checked those existed variables. If I want to add "weight" to reminder-box. It shows automatically lbs as its default unit. Now I change it to kgs. After that, if I want to add a new measurement, the default unit is Kgs and user no need to set it again. So I am asking the same mechanism for those non-existed variables. Is it possible or?

**Comment by mikepsinn** [comment]
I think it should work the same.  Have you noticed it not remembering in the last 2 days since I fixed them? @lavea

**Comment by lavea** [comment]
Tks! I guess I will try with a new version and if still have the same issue, will notify you then.

**Comment by mikepsinn** [comment]
#611
