### ISSUE TITLE
Windows: Alternative Install Dependencies

### ISSUE THREAD

**Issue by Thoughtscript** [QuantiModo/quantimodo-android-chrome-ios-web-app#1161]
Failure on build in Windows 10 - Node-Gyp Isn't Needed during install

**Comment by mikepsinn** [comment]
Thanks, @Thoughtscript !  However, I don't understand completely. I haven't had this problem on Windows 10.  So were you ultimately unable to get it installed?  Could you paste the error logs here?  Do you have a suggested change to package.json?

**Comment by ikhbarkhan** [comment]
Hebat
