### ISSUE TITLE
Responsive quick menu

### ISSUE THREAD

**Issue by in-zare** [QuantiModo/quantimodo-android-chrome-ios-web-app#1164]
On smaller screens such as iPhone 5 when the text is too long it doesn't fit the screen. (no problem on iPhone 6)
![img_2017-03-14 19 43 34](https://cloud.githubusercontent.com/assets/18409221/23917788/3bfa3c8e-08f9-11e7-99ec-a3cf2505c67d.jpg)

**Comment by mikepsinn** [comment]
Thanks @in-zare !

Fixed with https://github.com/QuantiModo/quantimodo-android-chrome-ios-web-app/pull/1165/commits/5a714b91ccc37175d2f75b3b50e34a92c9d7c58b
